# Generated by Django 3.0.8 on 2020-10-15 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
